package com.example.skill_ladder.navigation;


import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.fragment.app.Fragment;

import android.os.Environment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;


import com.example.skill_ladder.R;
import com.example.skill_ladder.model.showCustomToast;
import com.google.android.gms.tasks.OnFailureListener;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.QuerySnapshot;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.HorizontalAlignment;


import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;


public class GetReportsFragment extends Fragment {

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

                View view =  inflater.inflate(R.layout.fragment_get_reports, container, false);

        ImageView Uesrs = view.findViewById(R.id.Dowmload01);
        Uesrs.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                generateUserPDF();
            }
        });
        ImageView Lessons = view.findViewById(R.id.Dowmload02);
        Lessons.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                generateLessonsPDF();
            }
        });
        ImageView Company = view.findViewById(R.id.Dowmload03);
        Company.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                generateCompanyPDF();
            }
        });
        ImageView Job = view.findViewById(R.id.Dowmload04);
        Job.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                generateJobPDF();
            }
        });

        return view;
    }
    private void generateUserPDF() {

        FirebaseFirestore firestore = FirebaseFirestore.getInstance();
        firestore.collection("user")
                .whereEqualTo("isActive",true)
                .get()
                .addOnSuccessListener(new OnSuccessListener<QuerySnapshot>() {
                    @Override
                    public void onSuccess(QuerySnapshot queryDocumentSnapshots) {
                        try {
                            String path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).toString() + "/SkillLadder_Users_Report.pdf";
                            PdfWriter writer = new PdfWriter(path);
                            PdfDocument pdfDocument = new PdfDocument(writer);
                            Document document = new Document(pdfDocument);

                            Paragraph title = new Paragraph("SkillLadder Users Report").setBold().setFontSize(18);
                            document.add(title);

                            Paragraph date = new Paragraph("Generated on: " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(new Date()));
                            document.add(date);
                            Paragraph sig = new Paragraph("Generated by SkillLadder System\n© 2025 SkillLadder ");
                            document.add(sig);
                            document.add(new Paragraph("\n"));

                            Table table = new Table(new float[]{3, 4, 3})
                                    .useAllAvailableWidth()
                                    .setHorizontalAlignment(HorizontalAlignment.CENTER);

                            table.addCell(new Cell().add(new Paragraph("Name").setBold()));
                            table.addCell(new Cell().add(new Paragraph("Email").setBold()));
                            table.addCell(new Cell().add(new Paragraph("Mobile").setBold()));

                            for (DocumentSnapshot doc : queryDocumentSnapshots) {
                                String fullName = doc.getString("fullName");
                                String email = doc.getString("email");
                                String mobile = doc.getString("mobile");

                                table.addCell(fullName != null ? fullName : "N/A");
                                table.addCell(email != null ? email : "N/A");
                                table.addCell(mobile != null ? mobile : "N/A");
                            }
                            document.add(table);
                            document.close();
                            showCustomToast.showToast(getContext(),"PDF saved in Downloads",R.drawable.checked);

                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                }).addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        showCustomToast.showToast(requireActivity(), "Can't load User Data !", R.drawable.cancel);
                    }
                });
    }

    private void generateLessonsPDF() {

        FirebaseFirestore firestore = FirebaseFirestore.getInstance();
        firestore.collection("lessons")
                .whereEqualTo("active", true)
                .get()
                .addOnSuccessListener(new OnSuccessListener<QuerySnapshot>() {
                    @Override
                    public void onSuccess(QuerySnapshot queryDocumentSnapshots) {
                        try {
                            String path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).toString() + "/SkillLadder_Lessons_Report.pdf";
                            PdfWriter writer = new PdfWriter(path);
                            PdfDocument pdfDocument = new PdfDocument(writer);
                            Document document = new Document(pdfDocument);

                            Paragraph title = new Paragraph("SkillLadder Lessons Report").setBold().setFontSize(18);
                            document.add(title);

                            Paragraph date = new Paragraph("Generated on: " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(new Date()));
                            document.add(date);
                            Paragraph sig = new Paragraph("Generated by SkillLadder System\n© 2025 SkillLadder ");
                            document.add(sig);
                            document.add(new Paragraph("\n"));

                            Table table = new Table(new float[]{3, 3, 3, 2})
                                    .useAllAvailableWidth()
                                    .setHorizontalAlignment(HorizontalAlignment.CENTER);

                            table.addCell(new Cell().add(new Paragraph("Lesson Name").setBold()));
                            table.addCell(new Cell().add(new Paragraph("Lesson Field").setBold()));
                            table.addCell(new Cell().add(new Paragraph("Lesson Title").setBold()));
                            table.addCell(new Cell().add(new Paragraph("Lesson Price").setBold()));

                            for (DocumentSnapshot doc : queryDocumentSnapshots) {
                                String jobField = doc.getString("jobField");
                                String jobTitle = doc.getString("jobTitle");
                                String lessonName = doc.getString("lessonName");
                                Integer price = doc.getLong("price").intValue();
                                String price01 = String.valueOf(price);

                                table.addCell(lessonName != null ? lessonName : "N/A");
                                table.addCell(jobField != null ? jobField : "N/A");
                                table.addCell(jobTitle != null ? jobTitle : "N/A");
                                table.addCell(price01 != null ? price01 : "N/A");
                            }
                            document.add(table);
                            document.close();
                            showCustomToast.showToast(getContext(), "PDF saved in Downloads", R.drawable.checked);

                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                }).addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        showCustomToast.showToast(requireActivity(), "Can't load Lessons Data !", R.drawable.cancel);
                    }
                });
    }
    private void generateCompanyPDF() {

        FirebaseFirestore firestore = FirebaseFirestore.getInstance();
        firestore.collection("company")
                .whereEqualTo("isActive",true)
                .get()
                .addOnSuccessListener(new OnSuccessListener<QuerySnapshot>() {
                    @Override
                    public void onSuccess(QuerySnapshot queryDocumentSnapshots) {
                        try {
                            String path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).toString() + "/SkillLadder_Company_Report.pdf";
                            PdfWriter writer = new PdfWriter(path);
                            PdfDocument pdfDocument = new PdfDocument(writer);
                            Document document = new Document(pdfDocument);

                            Paragraph title = new Paragraph("SkillLadder Company Report").setBold().setFontSize(18);
                            document.add(title);

                            Paragraph date = new Paragraph("Generated on: " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(new Date()));
                            document.add(date);
                            Paragraph sig = new Paragraph("Generated by SkillLadder System\n© 2025 SkillLadder ");
                            document.add(sig);
                            document.add(new Paragraph("\n"));

                            Table table = new Table(new float[]{3, 4, 3})
                                    .useAllAvailableWidth()
                                    .setHorizontalAlignment(HorizontalAlignment.CENTER);

                            table.addCell(new Cell().add(new Paragraph("Company Name").setBold()));
                            table.addCell(new Cell().add(new Paragraph("Company Email").setBold()));
                            table.addCell(new Cell().add(new Paragraph("Company Mobile").setBold()));

                            for (DocumentSnapshot doc : queryDocumentSnapshots) {
                                String name = doc.getString("name");
                                String email = doc.getString("email");
                                String mobile = doc.getString("mobile");

                                table.addCell(name != null ? name : "N/A");
                                table.addCell(email != null ? email : "N/A");
                                table.addCell(mobile != null ? mobile : "N/A");
                            }
                            document.add(table);
                            document.close();
                            showCustomToast.showToast(getContext(),"PDF saved in Downloads",R.drawable.checked);

                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                }).addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        showCustomToast.showToast(requireActivity(), "Can't load Company Data !", R.drawable.cancel);
                    }
                });
    }
    private void generateJobPDF() {

        FirebaseFirestore firestore = FirebaseFirestore.getInstance();
        firestore.collection("jobs")
                .get()
                .addOnSuccessListener(new OnSuccessListener<QuerySnapshot>() {
                    @Override
                    public void onSuccess(QuerySnapshot queryDocumentSnapshots) {
                        try {
                            String path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).toString() + "/SkillLadder_Job_Report.pdf";
                            PdfWriter writer = new PdfWriter(path);
                            PdfDocument pdfDocument = new PdfDocument(writer);
                            Document document = new Document(pdfDocument);

                            Paragraph title = new Paragraph("SkillLadder Job Report").setBold().setFontSize(18);
                            document.add(title);

                            Paragraph date = new Paragraph("Generated on: " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(new Date()));
                            document.add(date);
                            Paragraph sig = new Paragraph("Generated by SkillLadder System\n© 2025 SkillLadder ");
                            document.add(sig);
                            document.add(new Paragraph("\n"));

                            Table table = new Table(new float[]{2, 3, 3, 3, 3})
                                    .useAllAvailableWidth()
                                    .setHorizontalAlignment(HorizontalAlignment.CENTER);

                            table.addCell(new Cell().add(new Paragraph("Company Name").setBold()));
                            table.addCell(new Cell().add(new Paragraph("Company Email").setBold()));
                            table.addCell(new Cell().add(new Paragraph("Company Mobile").setBold()));
                            table.addCell(new Cell().add(new Paragraph("Job Vacancy").setBold()));
                            table.addCell(new Cell().add(new Paragraph("Closing Date").setBold()));

                            for (DocumentSnapshot doc : queryDocumentSnapshots) {
                                String CompanyName = doc.getString("CompanyName");
                                String CompanyEmail = doc.getString("CompanyEmail");
                                String CompanyMobile = doc.getString("CompanyMobile");
                                String ClosingDate = doc.getString("ClosingDate");
                                String JobTitle = doc.getString("JobTitle");

                                table.addCell(CompanyName != null ? CompanyName : "N/A");
                                table.addCell(CompanyEmail != null ? CompanyEmail : "N/A");
                                table.addCell(CompanyMobile != null ? CompanyMobile : "N/A");
                                table.addCell(JobTitle != null ? JobTitle : "N/A");
                                table.addCell(ClosingDate != null ? ClosingDate : "N/A");

                            }
                            document.add(table);
                            document.close();
                            showCustomToast.showToast(getContext(),"PDF saved in Downloads",R.drawable.checked);

                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                }).addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        showCustomToast.showToast(requireActivity(), "Can't load Company Data !", R.drawable.cancel);
                    }
                });
    }
}